# Generated by Django 4.1.6 on 2023-04-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='source',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
