# Generated by Django 4.1.6 on 2023-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_privatepostviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='origin',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='source',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
