# Generated by Django 4.1.6 on 2023-03-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_comments_id_posts_id_posts_origin_posts_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profileImage',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
