# Generated by Django 4.1.6 on 2023-03-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profileImage',
        ),
    ]
