# Generated by Django 4.1.6 on 2023-03-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_posts_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.TextField(blank=True, default='[]', max_length=300, null=True),
        ),
    ]
