# Generated by Django 4.1.6 on 2023-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
