# Generated by Django 4.1.6 on 2023-03-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_remove_inbox_type_inbox_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='viewed',
        ),
    ]
