# Generated by Django 4.1.6 on 2023-03-27 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('inbox', '0003_remove_inbox_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='follow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.followingrequest'),
        ),
    ]
