# Generated by Django 4.1.6 on 2023-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='host',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
