# Generated by Django 4.1.6 on 2023-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
