# Generated by Django 4.1.6 on 2023-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
