# Generated by Django 4.1.6 on 2023-02-22 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_visbility', models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('V', 'Private')], default='V', max_length=1)),
                ('published', models.TimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=300)),
                ('unlisted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
