# Generated by Django 4.1.6 on 2023-02-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_visibility',
            new_name='visibility',
        ),
    ]
