# Generated by Django 4.1.6 on 2023-02-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_posts_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain'), ('text/markdown', 'Markdown'), ('application/base64', 'Base64'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpeg')], default='text/plain', max_length=200),
        ),
    ]
