# Generated by Django 4.1.6 on 2023-03-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='privatepostviewer',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='privatepostviewer',
            name='viewer_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='PrivatePostViewer',
        ),
    ]
