# Generated by Django 4.1.6 on 2023-02-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_privatepostviewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_visbility',
            new_name='post_visibility',
        ),
    ]
