# Generated by Django 4.1.6 on 2023-02-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_images'),
        ('base', '0007_privatepostviewer_delete_privatepostviewers'),
    ]

    operations = [
    ]
