# Generated by Django 4.1.6 on 2023-02-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20230224_0826'),
        ('base', '0011_alter_comments_content'),
    ]

    operations = [
    ]
