# Generated by Django 4.1.6 on 2023-02-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_merge_20230225_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comments'),
        ),
    ]
